version: '3'

services:

  rproxy:
    container_name: rproxy
    hostname: rproxy
    image: nginx:stable-alpine
    ports: 
      - 80:80
      - 433:433
    volumes:
      - ./rproxy/nginx.conf:/etc/nginx/nginx.conf

  web:
    image: djfinnoy/didjfin-web
    container_name: web
    hostname: web
    ports:
      - 8081:8081
  
  shiny:
    image: djfinnoy/didjfin-shiny
    container_name: shiny
    hostname: shiny
    ports:
      - 3838:3838
